name: chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.11.0
  file_picker: ^6.0.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  firebase_storage: ^11.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_screenutil: ^5.8.4
  fpdart: ^1.1.0
  grouped_list: ^5.1.2
  hooks_riverpod: ^2.4.4
  image_picker: ^1.0.4
  intl: ^0.18.1
  path: ^1.8.3
  print_color: ^3.0.5
  rxdart: ^0.27.7
  separated_column: ^2.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900

    - family: Bungee
      fonts:
        - asset: assets/fonts/bungee/Bungee-Regular.ttf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/assets/
  filename: assets.dart
  field_prefix: null
