// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi6edTV0BUD8NUxopV0SyrkLMvhzXh6cU',
    appId: '1:376748379776:web:d0b31f5a9211a6de566065',
    messagingSenderId: '376748379776',
    projectId: 'flutter-chat-6948a',
    authDomain: 'flutter-chat-6948a.firebaseapp.com',
    storageBucket: 'flutter-chat-6948a.appspot.com',
    measurementId: 'G-L3KTD8CTJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALcRN4hOKR9LezuDp7UNozhtsJEvRqmas',
    appId: '1:376748379776:android:aeda86a60b90fa59566065',
    messagingSenderId: '376748379776',
    projectId: 'flutter-chat-6948a',
    storageBucket: 'flutter-chat-6948a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7DLw7jCbveV0ybBO8pgAgSqe4THAuFBI',
    appId: '1:376748379776:ios:da23d7f2a3bcd556566065',
    messagingSenderId: '376748379776',
    projectId: 'flutter-chat-6948a',
    storageBucket: 'flutter-chat-6948a.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7DLw7jCbveV0ybBO8pgAgSqe4THAuFBI',
    appId: '1:376748379776:ios:b39b21b65efb27bc566065',
    messagingSenderId: '376748379776',
    projectId: 'flutter-chat-6948a',
    storageBucket: 'flutter-chat-6948a.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
